[package]
name = "hw0"
version = "0.1.0"
authors = ["Ignat Loskutov <ignat.loskutov@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[dependencies]
regex = "0.2"
lalrpop-util = "0.14"

[build-dependencies]
lalrpop= "0.14"
